name: Deploy ASP.NET API to Azure

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./CreditDecision.sln

    - name: Build
      run: dotnet build ./CreditDecision.sln --no-restore --configuration Release

    - name: Publish
      run: dotnet publish ./CreditDecision.sln --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: CreditDecisionAppAPI
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: ./publish
